function stressPhasePlot(initTime,minMax,ORDER,START,END,specColor)
%STRESSPHASEPLOT Summary of this function goes here
%   Detailed explanation goes here
for classIdx = 1:length(ORDER)
    if specColor
        if minMax(1) > 0 && minMax(1) > minMax(2)*0.1
            area([initTime+minutes(START(classIdx)),initTime+minutes(END(classIdx))],...
                [minMax(2)*1.1,minMax(2)*1.1],...
                minMax(1)*0.9, 'FaceAlpha',0.3,'EdgeColor', 'none','FaceColor',[0.8500, 0.3250, 0.0980])
        elseif minMax(1) > 0 && minMax(1) < 1
            area([initTime+minutes(START(classIdx)),initTime+minutes(END(classIdx))],...
                [minMax(2)*1.1,minMax(2)*1.1],...
                minMax(1)-(0.1*minMax(2)), 'FaceAlpha',0.3,'EdgeColor', 'none','FaceColor',[0.8500, 0.3250, 0.0980])
        else
            area([initTime+minutes(START(classIdx)),initTime+minutes(END(classIdx))],...
                [minMax(2)*1.1,minMax(2)*1.1],...
                minMax(1)*1.1, 'FaceAlpha',0.3,'EdgeColor', 'none','FaceColor',[0.8500, 0.3250, 0.0980])
        end
    else
        if minMax(1) > 0 && minMax(1) > minMax(2)*0.1
            area([initTime+minutes(START(classIdx)),initTime+minutes(END(classIdx))],...
                [minMax(2)*1.1,minMax(2)*1.1],...
                minMax(1)*0.9, 'FaceAlpha',0.3,'EdgeColor', 'none')
        elseif minMax(1) > 0 && minMax(1) < 1
            area([initTime+minutes(START(classIdx)),initTime+minutes(END(classIdx))],...
                [minMax(2)*1.1,minMax(2)*1.1],...
                minMax(1)-(0.1*minMax(2)), 'FaceAlpha',0.3,'EdgeColor', 'none')
        else
            area([initTime+minutes(START(classIdx)),initTime+minutes(END(classIdx))],...
                [minMax(2)*1.1,minMax(2)*1.1],...
                minMax(1)*1.1, 'FaceAlpha',0.3,'EdgeColor', 'none')
        end
    end
    
end
end

